### ISSUE TITLE
Simplify typedef forward declarations

### ISSUE THREAD

**Issue by meshula** [OpenTimelineIO/OpenTimelineIO-C-Bindings#4]
Simplify typedef forward declarations. c.f. https://github.com/PixarAnimationStudios/OpenTimelineIO/commit/e17be4ff4a0eeb618a7e8af7a5228481fbfa62d3

**Comment by KarthikRIyer** [comment]
@meshula We can close this too. Fixed in last PR.

**Comment by meshula** [comment]
For future PRs, referencing issues in the PR actually invokes an auto-close, which is a nifty feature.

**Comment by KarthikRIyer** [comment]
Yes. I'll remember that from next time. 

I hadn't checked this issue before making the PR, so didn't reference it there.
